### ISSUE TITLE
[Bug] Undoing parented object causes others to disappear temporarily

### ISSUE THREAD

**Issue by SarahGreyWolf** [Nebual/sandbox-plus#17]
If you use the Parent tool (in sandbox terms, weld) a bunch of props together and then undo one of the props, the others that were welded to the undone prop will temporarily vanish, before returning a few seconds later.
This could be an issue with S&Box itself but since it doesn't happen with the remove tool I assume it's related to undo.
I should say that the props don't actually dissapear, they still exist and can be collided with and even shot, though the phys and gravity guns cannot seem to interact with them.

**Comment by ninjrdevelop** [comment]
Probably worth closing this as the undo system has been rewritten. Happy to reopen if still relevant in the parenting tool (not implemented in pending MR)
