### ISSUE TITLE
[Bug] Weird PhysGun beam start location behavior

### ISSUE THREAD

**Issue by Hri7566** [Nebual/sandbox-plus#26]
I don't quite understand what causes this, but it's fairly frequent in singleplayer.

![image](https://github.com/Nebual/sandbox-plus/assets/18133844/cd4cbc68-4942-4ffd-b47c-83d55d19cde6)

**Comment by Hri7566** [comment]
PS doesn't happen in first person

**Comment by ninjrdevelop** [comment]
Not replicated in current version. Reopen if we can get it to happen again.
