### ISSUE TITLE
[Improvement] Rewrite Player class to use Pawns

### ISSUE THREAD

**Issue by Hri7566** [Nebual/sandbox-plus#29]
Player class was used in the original sandbox mode, but is deprecated now.

This one will probably take a lot longer.

**Comment by Nebual** [comment]
I believe SnakeSVx of Spacebuild is looking at replacing our Player class, likely with a better collision/movement model including supporting dynamic gravity, so if anyone's looking to collaborate they may want to reach out in the Spacebuild discord :)

**Comment by Nebual** [comment]
Probably less/differently applicable as of the Scene update
