### ISSUE TITLE
Weapons spawn in random order sometimes

### ISSUE THREAD

**Issue by Nebual** [Nebual/sandbox-plus#30]
I can't reproduce it consistently, but sometimes you spawn with your inventory in a random order, which is a nuisance. Not sure why...

**Comment by Hri7566** [comment]
Happens in original sandbox gamemode, probably a race condition

**Comment by ninjrdevelop** [comment]
Related to this, do we ensure it's sorted by implementing the original stacked inventory slots system?

That should help ensure we're spawning weapons in consistent slots.

E.g, spawn in weapon slot 4, subslot 1

**Comment by ninjrdevelop** [comment]
I killed myself in local multiplayer at least a dozen or two times today and couldn't get this to happen. Makes me wonder if this was an issue in a previous edition of our code :)

If that level of reliability seems to beat your experience last year, @Nebual, we can close this off for now?
