### ISSUE TITLE
[Bug] Double-space noclip shortcut only works when no other keys are pressed

### ISSUE THREAD

**Issue by Hri7566** [Nebual/sandbox-plus#34]
When pressing space twice to toggle noclip, no other keys can be held at the same time.

**Comment by Kolya142** [comment]
from original sandbox mode

**Comment by Kolya142** [comment]
i found it:
if ( InputDirection.y != 0 || InputDirection.x != 0f )
{
	timeSinceJumpReleased = 1;
}
file: code/Player.cs, line: 184

**Comment by ninjrdevelop** [comment]
This doesn't appear to be relevant anymore, as Noclip is only triggered by the Noclip bind, as far as I can see
`IsNoclipping = Input.Pressed( "noclip" ) ? !IsNoclipping : IsNoclipping;`
