### ISSUE TITLE
[Bug] PhysGun laser sound sometimes doesn't stop when it's supposed to

### ISSUE THREAD

**Issue by Hri7566** [Nebual/sandbox-plus#35]
Sometimes, the laser sound of the physics gun doesn't stop and will continue after letting go of `attack1`.

Temporary fix: `stopsound`

**Comment by Hri7566** [comment]
This also happens rarely with the gravity gun hover sound I added in #24

**Comment by Nebual** [comment]
I think I fixed this in d45dcc4e5df3ad5e4acd97917ac96f55d3efb81f - `Sound.IsPlaying` is often wrong for a few ticks after it first starts, which in this case led to us creating multiple sounds at once, with only one of them being tracked and disabled on release.
