### ISSUE TITLE
Fix 3rd person terry walking

### ISSUE THREAD

**Issue by ninjrdevelop** [Nebual/sandbox-plus#53]
![image](https://github.com/user-attachments/assets/cf40eb8c-8eb9-46b3-ac9c-99c7ef2b5db1)

**Comment by Nebual** [comment]
May possibly be fixed by https://github.com/Softsplit/sandbox-classic/commit/96326400bfb976bad132771cdef44dbcd4d75d5d or the 2 commits right after

**Comment by ninjrdevelop** [comment]
You fixed it by bringing in those commits. Likely af6981e97462a41dfc17f6491b3d3b3c813a4afb
