### ISSUE TITLE
[Bug] Addon Select Filter Stuck

### ISSUE THREAD

**Issue by SarahGreyWolf** [Nebual/sandbox-plus#8]
Once you've filtered the addon select menu on the main menu to something, for example Maps, you enter the maps filter and get new filtering options however there is no way to go back to the global list

**Comment by Nebual** [comment]
I've disabled the ability to select types other than Addon in that menu, which should fix this. Also, I've filtered out npc/entity addons, since those don't make sense to load on boot, thats what the Spawnmenu's entities list is for.
